services:
    balloon-popper:
        image: ghcr.io/kameshsampath/stream-demos-datagen/balloon-popper:latest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_LOG_LEVEL=DEBUG
        entrypoint:
            - /app/bin/entrypoint
        command:
            - "--topic=balloon-game"
            - "--bootstrap-servers=kafka:29092"
            - "--delay=1"
        networks:
            - iceberg
networks:
  iceberg:
    external: true
    name: iceberg_demos_iceberg
